// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
import "dotenv/config";
import { defineConfig } from "prisma/config";
import { lodVariable } from "./src/utils/dotenv.js";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: lodVariable("DATABASE_URL"),
  },
});
